### ISSUE TITLE
compile issues with pg 9.6

### ISSUE THREAD

**Issue by tanglebones** [tanglebones/pg_tuid#3]
```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument  -mmacosx-version-min=10.7  -L/Applications/Postgres.app/Contents/Versions/9.6/lib -L/Applications/Postgres.app/Contents/Versions/9.6/lib  -L/Applications/Postgres.app/Contents/Versions/9.6/lib -Wl,-dead_strip_dylibs   -bundle -bundle_loader /Applications/Postgres.app/Contents/Versions/9.6/bin/postgres -o tuid.so tuid.o
Undefined symbols for architecture x86_64:
  "_LWLockAssign", referenced from:
      _tuid_shmem_startup in tuid.o
  "_RequestAddinLWLocks", referenced from:
      __PG_init in tuid.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by tanglebones** [comment]
It's compiling with 9.6 now, but segfaults when run. I suspect the redone locking code is incorrect.

**Comment by leoc** [comment]
Does it work with 9.5?

What do you think might be the problem here? I have never developed postgres extensions, but I found these posts:

https://www.postgresql.org/message-id/13370.1272422082%40sss.pgh.pa.us
http://paquier.xyz/postgresql-2/postgres-10-highlight-shmem-alloc/

Do we have to check the return value of `ShmemInitStruct` ?

I'd love to help, do you have some resources you worked with?

**Comment by tanglebones** [comment]
I didn't think anyone was using this, but if you are I will take a look at
it later today. It is something to do with the lock changes between 9.4 and
9.6.

**Comment by tanglebones** [comment]
I was largely basing the code off of https://doxygen.postgresql.org/pg__stat__statements_8c_source.html

**Comment by tanglebones** [comment]
looks like `shmem_startup_hook` never gets called.

**Comment by tanglebones** [comment]
fixed in #3cb21c0

**Comment by leoc** [comment]
I did not think you would respond so quickly! You're awesome!
Thanks a lot.

![giphy-downsized](https://cloud.githubusercontent.com/assets/184696/26679696/88f580aa-46d6-11e7-807b-5d58a5df5be2.gif)

Have you been using this for any project yet?

**Comment by tanglebones** [comment]
I use the sql and ruby versions already in production.

I did the C version before realizing that RDS and aiven.io won't run custom
C plugins. Where I work at now we are not ready to move off a managed
provider, so we can't use the C version.
